
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "#{$path_prefix}test"
  t.libs << "#{$path_prefix}share/ruby"
  t.test_files = FileList["#{$path_prefix}test/*_test.rb"]
end

task default: :test
