Layout/LineLength:
  Max: 150
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Metrics/MethodLength:
  Max: 32
  Exclude:
    - test/*
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 39
  Exclude:
    - test/*
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 8
Metrics/ParameterLists:
  Max: 6

Naming/AccessorMethodName:
  Enabled: false

Style/StderrPuts:
  Enabled: false 
Style/PercentLiteralDelimiters:
  Enabled: false  
Style/Documentation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false


AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'share/ruby/vendor/**/*'
    - test/*
