#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _APPTOKIT_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

export APPTOKIT_RUBY_SHARE_PATH="$_APPTOKIT_ROOT/share/ruby"
export APPTOKIT_RUBY_VENDOR_PATH="$_APPTOKIT_ROOT/share/ruby/vendor"

ruby_version_major=$(ruby --disable-gems -e "print RUBY_VERSION.split('.').tap {|a| a[2] = '0'}.join('.')")
export GEM_PATH="${APPTOKIT_RUBY_VENDOR_PATH}/ruby/${ruby_version_major}:${GEM_PATH}"
export RUBYLIB="$APPTOKIT_RUBY_SHARE_PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec apptokit-help
  ;;
* )
  command_path="$(command -v "apptokit-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "apptokit: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
