#!/usr/bin/env ruby
# frozen_string_literal: true

# Usage: apptokit app-token
# Summary: Generate a JWT for your GitHub App
# Help:
#   Pulls config from the .apptokit.yml file.

require "setup"
require "apptokit/jwt"

jwt = Apptokit::JWT.generate

if $stdout.isatty
  puts "Your JWT: \n#{jwt.token}"
else
  print "Bearer #{jwt.token}"
end
