#!/usr/bin/env ruby
# Usage: apptokit installation-token [--force]
# Summary: Generate an installation token for a GitHub App installation.
# Help: Generates an installation token for your app
# - --force will ignore a cached token if one exists for your installation.

require "setup"
require "apptokit/installation_token"

force = (%w(-f --force) & ARGV).any?

token = Apptokit::InstallationToken.generate(skip_cache: force)

if $stdout.isatty
  puts "Your token:"
  puts token.token
  puts "expires at: #{token.expires_at}"
else
  print token.header
end
