#!/usr/bin/env ruby
# Usage: apptokit installation-token
# Summary: Generate an installation token for a GitHub App installation.

require "setup"
require "apptokit/installation_token"

token = Apptokit::InstallationToken.generate

if $stdout.isatty
  puts "Your token:"
  puts token.token
  puts "expires at: #{token.expires_at}"
else
  print token.header
end
